#!/bin/bash

# Set /work as current working dir inside container
# Mount current dir as /work inside container
# Mount in creds
docker run -it --rm \
  -w /work \
  -v $PWD:/work \
  -v ~/.aws:/root/.aws \
  -v ~/.elasticbeanstalk:/root/.elasticbeanstalk \
  -v ~/.ssh:/root/.ssh \
  adzdavies/awsebcli "$@"
